// pkg/darwin/mutator.go — Genetic Mutation Engine. [SRE-93.B]
//
// Generates algorithmic variants of a function via LLM (Ollama), evaluates
// them in parallel via benchmark, and runs multi-generation evolution to
// find the optimal implementation.
package darwin

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"regexp"
	"strings"
	"sync"
	"time"

	"github.com/ensamblatec/neoanvil/pkg/sre"
)

// Mutation is a single algorithmic variant generated by the LLM. [SRE-93.B.1]
type Mutation struct {
	ID         int    `json:"id"`
	Generation int    `json:"generation"`
	Source     string `json:"source"`
}

// EvalResult is the benchmark result of a single mutation. [SRE-93.B.2]
type EvalResult struct {
	MutationID   int     `json:"mutation_id"`
	Generation   int     `json:"generation"`
	Compiles     bool    `json:"compiles"`
	NsPerOp      int64   `json:"ns_per_op"`
	AllocsPerOp  int64   `json:"allocs_per_op"`
	Improvement  float64 `json:"improvement_pct"` // positive = faster
	Error        string  `json:"error,omitempty"`
}

// Champion is the best mutation found across all generations. [SRE-93.B.3]
type Champion struct {
	Source         string  `json:"source"`
	NsPerOp        int64   `json:"ns_per_op"`
	AllocsPerOp    int64   `json:"allocs_per_op"`
	ImprovementPct float64 `json:"improvement_pct"`
	Generation     int     `json:"generation"`
	MutationID     int     `json:"mutation_id"`
}

// GenerateMutations sends the source function to Ollama and parses N variants
// from the response. Returns at most `count` mutations. [SRE-93.B.1]
func GenerateMutations(source string, count int, ollamaURL, model string, client *http.Client) ([]Mutation, error) {
	prompt := fmt.Sprintf(`You are a Go performance optimization expert. Given this Go function:

%s

Generate %d algorithmically different implementations that:
1. Produce the EXACT same output for all inputs
2. Optimize for: fewer allocations, lower latency
3. Use different algorithmic approaches (not just cosmetic changes)

Return each variant wrapped in triple backticks with "go" language tag.
Number each variant (Variant 1, Variant 2, etc.)`, source, count)

	body, marshalErr := json.Marshal(map[string]any{
		"model":  model,
		"prompt": prompt,
		"stream": false,
		"options": map[string]any{
			"temperature": 0.8,
			"num_predict": 4096,
		},
	})
	if marshalErr != nil {
		return nil, fmt.Errorf("marshal request: %w", marshalErr)
	}

	req, err := http.NewRequest(http.MethodPost, ollamaURL+"/api/generate", bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("ollama request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(io.LimitReader(resp.Body, 1024))
		return nil, fmt.Errorf("ollama status %d: %s", resp.StatusCode, string(respBody))
	}

	var result struct {
		Response string `json:"response"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("decode ollama response: %w", err)
	}

	return parseGoBlocks(result.Response, count), nil
}

// parseGoBlocks extracts Go code blocks from the LLM response.
var codeBlockRE = regexp.MustCompile("(?s)```go\\s*\\n(.*?)```")

func parseGoBlocks(text string, maxCount int) []Mutation {
	matches := codeBlockRE.FindAllStringSubmatch(text, -1)
	var mutations []Mutation
	for i, m := range matches {
		if i >= maxCount {
			break
		}
		src := strings.TrimSpace(m[1])
		if src == "" {
			continue
		}
		mutations = append(mutations, Mutation{
			ID:     i + 1,
			Source: src,
		})
	}
	return mutations
}

// EvaluateGeneration benchmarks a batch of mutations in parallel (up to
// maxParallel at a time) against the baseline. [SRE-93.B.2]
func EvaluateGeneration(mutations []Mutation, baselineNs int64, benchmarkFn func(source string) (BenchmarkResult, error), maxParallel int) []EvalResult {
	if maxParallel <= 0 {
		maxParallel = 10
	}
	results := make([]EvalResult, len(mutations))
	sem := make(chan struct{}, maxParallel)
	var wg sync.WaitGroup

	for i := range mutations {
		wg.Add(1)
		go func(idx int) {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()

			m := mutations[idx]
			br, err := benchmarkFn(m.Source)

			res := EvalResult{
				MutationID:  m.ID,
				Generation:  m.Generation,
				NsPerOp:     br.NsPerOp,
				AllocsPerOp: br.AllocsPerOp,
			}
			if err != nil {
				res.Compiles = false // [SRE-96.A.2] explicit false on error
				res.Error = err.Error()
			} else {
				res.Compiles = br.Compiled
			}
			if br.Compiled && baselineNs > 0 {
				res.Improvement = float64(baselineNs-br.NsPerOp) / float64(baselineNs) * 100
			}
			results[idx] = res
		}(i)
	}
	wg.Wait()
	return results
}

// RunEvolution runs multi-generation evolution: generate → benchmark → select
// top performers → use as seeds for next generation. Returns the best overall
// champion. [SRE-93.B.3]
func RunEvolution(hotspot Hotspot, cfg EvolutionConfig, client *http.Client, benchmarkFn func(string) (BenchmarkResult, error)) (Champion, error) {
	log.Printf("[DARWIN] Starting evolution for %s.%s (%d generations, pop %d)",
		hotspot.Package, hotspot.Function, cfg.Generations, cfg.PopulationSize)

	// Extract the original source.
	source, imports, err := ExtractFunction(hotspot.File, hotspot.Function)
	if err != nil {
		return Champion{}, fmt.Errorf("extract function: %w", err)
	}

	// Benchmark the baseline.
	baselineResult, err := benchmarkFn(GenerateBenchmarkSource(source, imports, cfg.BenchmarkIters))
	if err != nil {
		return Champion{}, fmt.Errorf("baseline benchmark: %w", err)
	}
	baselineNs := baselineResult.NsPerOp
	log.Printf("[DARWIN] Baseline: %d ns/op, %d allocs/op", baselineNs, baselineResult.AllocsPerOp)

	var bestChampion Champion
	seedSource := source

	for gen := 1; gen <= cfg.Generations; gen++ {
		log.Printf("[DARWIN] Generation %d/%d — generating %d mutations", gen, cfg.Generations, cfg.PopulationSize)

		mutations, genErr := GenerateMutations(seedSource, cfg.PopulationSize, cfg.OllamaURL, cfg.Model, client)
		if genErr != nil {
			log.Printf("[DARWIN] Generation %d failed to generate mutations: %v", gen, genErr)
			continue
		}

		// Tag generation.
		for i := range mutations {
			mutations[i].Generation = gen
		}

		// [SRE-96.A.2] Wrap each mutation in a compilable benchmark harness before evaluation.
		wrappedBenchmarkFn := func(source string) (BenchmarkResult, error) {
			wrapped := GenerateBenchmarkSource(source, imports, cfg.BenchmarkIters)
			return benchmarkFn(wrapped)
		}
		results := EvaluateGeneration(mutations, baselineNs, wrappedBenchmarkFn, cfg.PopulationSize)

		// Find the best in this generation.
		for _, r := range results {
			if !r.Compiles || r.Improvement <= 0 {
				continue
			}
			if r.Improvement > bestChampion.ImprovementPct {
				// Find the mutation source.
				for _, m := range mutations {
					if m.ID == r.MutationID {
						bestChampion = Champion{
							Source:         m.Source,
							NsPerOp:        r.NsPerOp,
							AllocsPerOp:    r.AllocsPerOp,
							ImprovementPct: r.Improvement,
							Generation:     gen,
							MutationID:     r.MutationID,
						}
						seedSource = m.Source // use as seed for next gen
						break
					}
				}
			}
		}

		if bestChampion.Source != "" {
			log.Printf("[DARWIN] Gen %d champion: mutation %d, %.1f%% faster",
				gen, bestChampion.MutationID, bestChampion.ImprovementPct)
		} else {
			log.Printf("[DARWIN] Gen %d: no improvement found", gen)
		}
	}

	if bestChampion.Source == "" {
		return Champion{}, fmt.Errorf("no improvement found after %d generations", cfg.Generations)
	}

	return bestChampion, nil
}

// EvolutionConfig holds parameters for RunEvolution. Populated from neo.yaml darwin section.
type EvolutionConfig struct {
	OllamaURL      string
	Model          string
	Generations    int
	PopulationSize int
	BenchmarkIters int
	TimeoutSec     int
}

// NewEvolutionConfigFromYAML creates an EvolutionConfig from the darwin section of neo.yaml.
func NewEvolutionConfigFromYAML(ollamaURL, model string, generations, popSize, benchIters, timeoutSec int) EvolutionConfig {
	return EvolutionConfig{
		OllamaURL:      ollamaURL,
		Model:          model,
		Generations:    generations,
		PopulationSize: popSize,
		BenchmarkIters: benchIters,
		TimeoutSec:     timeoutSec,
	}
}

// OllamaClient creates an HTTP client for Ollama with the configured timeout.
// [SRE-110.C] Uses SafeHTTPClient — Ollama URL is user-configured (potentially
// external), so the same SSRF guard as other LLM endpoints applies.
func OllamaClient(timeoutSec int) *http.Client {
	c := sre.SafeHTTPClient()
	c.Timeout = time.Duration(timeoutSec) * time.Second
	return c
}
