// pkg/federation/shared_incidents.go — SHARED_INCIDENTS.md helpers for Project Federation. [340]
//
// AppendSharedIncident logs a cross-boundary incident (one whose AffectedServices
// span multiple workspaces) into .neo-project/SHARED_INCIDENTS.md. The file is
// bootstrapped on first write and de-duplicated by incident ID on subsequent calls.
package federation

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const sharedIncidentsFile = "SHARED_INCIDENTS.md"
const sharedIncidentsSection = "## Cross-Workspace Incidents"

const incTableHeader = "| ID | Severity | Workspace | Services | Summary | Date |"
const incTableSep = "|----|----------|-----------|----------|---------|------|"

// AppendSharedIncident inserts a cross-boundary incident row into
// .neo-project/SHARED_INCIDENTS.md, creating the file when absent.
// Idempotent: skips the write if the incident ID is already present. [340]
func AppendSharedIncident(projectDir, id, severity, wsOrigin, anomaly string, services []string) error {
	path := filepath.Join(projectDir, sharedIncidentsFile)
	now := time.Now().UTC().Format("2006-01-02")
	svcStr := strings.Join(services, ", ")
	if svcStr == "" {
		svcStr = "_unknown_"
	}
	if len(anomaly) > 80 {
		anomaly = anomaly[:80] + "…"
	}
	newRow := fmt.Sprintf("| %s | %s | %s | %s | %s | %s |",
		id, severity, wsOrigin, svcStr, anomaly, now)

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	data, err := os.ReadFile(path) //nolint:gosec // G304-DIR-WALK: path is projectDir/SHARED_INCIDENTS.md under process control
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	content := string(data)

	// De-duplicate: skip if ID already present.
	if strings.Contains(content, "| "+id+" |") {
		return nil
	}

	newFooter := fmt.Sprintf("%s %s_", footerPrefix, now)

	if content == "" {
		// Bootstrap the file.
		content = fmt.Sprintf(
			"# Shared Incidents\n\n_Auto-generated by neo_radar INCIDENT_SEARCH scope:project — do not edit manually._\n\n%s\n\n%s\n%s\n%s\n\n%s\n",
			sharedIncidentsSection, incTableHeader, incTableSep, newRow, newFooter,
		)
		return os.WriteFile(path, []byte(content), 0o644) //nolint:gosec // G306-SHARED-SOCKET: public project doc
	}

	// Insert before existing footer or at end.
	lines := strings.Split(content, "\n")
	footerIdx := -1
	for i := len(lines) - 1; i >= 0; i-- {
		if strings.HasPrefix(strings.TrimSpace(lines[i]), footerPrefix) {
			footerIdx = i
			break
		}
	}
	if footerIdx >= 0 {
		lines[footerIdx] = newFooter
		// Insert row + blank line before footer.
		tail := append([]string{newRow, ""}, lines[footerIdx:]...)
		lines = append(lines[:footerIdx], tail...)
	} else {
		lines = append(lines, newRow, "", newFooter, "")
	}
	return os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0o644) //nolint:gosec // G306-SHARED-SOCKET: public project doc
}
